#include <nlohmann/json.hpp>
#include <cstdint>
#include <map>
#include <optional>
#include <set>
#include <string>
#include <vector>
using json=nlohmann::json;
namespace progressive{
struct UserProfile{std::string user_id,display_name,avatar_url;json to_json()const{json j;j["user_id"]=user_id;if(!display_name.empty())j["display_name"]=display_name;if(!avatar_url.empty())j["avatar_url"]=avatar_url;return j;}static UserProfile from_json(const json&j){return{j.value("user_id",""),j.value("display_name",""),j.value("avatar_url","")};}};
struct RoomInfo{std::string room_id,name,topic,canonical_alias,room_version;bool is_public;int64_t joined_members,invited_members;json to_json()const{return{{"room_id",room_id},{"name",name},{"topic",topic},{"canonical_alias",canonical_alias},{"room_version",room_version},{"is_public",is_public},{"joined_members",joined_members},{"invited_members",invited_members}};}static RoomInfo from_json(const json&j){RoomInfo r;r.room_id=j.value("room_id","");r.name=j.value("name","");r.topic=j.value("topic","");r.canonical_alias=j.value("canonical_alias","");r.room_version=j.value("room_version","1");r.is_public=j.value("is_public",false);r.joined_members=j.value("joined_members",0);r.invited_members=j.value("invited_members",0);return r;}};
struct EventDataStruct{std::string event_id,room_id,type,sender;std::optional<std::string> state_key;int64_t origin_server_ts,depth;json content;json to_json()const{json j{{"event_id",event_id},{"room_id",room_id},{"type",type},{"sender",sender},{"origin_server_ts",origin_server_ts},{"depth",depth},{"content",content}};if(state_key)j["state_key"]=*state_key;return j;}};
struct DeviceInfo{std::string device_id,display_name,last_seen_ip,user_agent;int64_t last_seen;bool hidden;json to_json()const{return{{"device_id",device_id},{"display_name",display_name},{"last_seen_ip",last_seen_ip},{"user_agent",user_agent},{"last_seen",last_seen},{"hidden",hidden}};}};
struct RoomMember{std::string user_id,display_name,avatar_url,membership;json to_json()const{return{{"user_id",user_id},{"display_name",display_name},{"avatar_url",avatar_url},{"membership",membership}};}};
struct PresenceState{std::string user_id,presence,status_msg;int64_t last_active_ago;bool currently_active;json to_json()const{return{{"user_id",user_id},{"presence",presence},{"status_msg",status_msg},{"last_active_ago",last_active_ago},{"currently_active",currently_active}};}};
struct PushRule{std::string rule_id,kind;int priority_class,priority;json conditions,actions;bool enabled,default_rule;json to_json()const{return{{"rule_id",rule_id},{"kind",kind},{"priority_class",priority_class},{"priority",priority},{"conditions",conditions},{"actions",actions},{"enabled",enabled},{"default",default_rule}};}};
struct ReceiptData{std::string room_id,user_id,event_id,receipt_type;int64_t ts;json data;json to_json()const{return{{"room_id",room_id},{"user_id",user_id},{"event_id",event_id},{"type",receipt_type},{"ts",ts},{"data",data}};}};
struct Filter{std::string filter_id;int64_t id;json definition;json to_json()const{return{{"filter_id",filter_id},{"id",id},{"definition",definition}};}};
struct RoomAlias{std::string room_alias,room_id,creator;json to_json()const{return{{"room_alias",room_alias},{"room_id",room_id},{"creator",creator}};}};
struct RoomTag{std::string user_id,room_id,tag;double order;json content;json to_json()const{return{{"user_id",user_id},{"room_id",room_id},{"tag",tag},{"order",order},{"content",content}};}};
struct AccountDataEntry{std::string user_id,data_type,room_id;json content;json to_json()const{json j{{"user_id",user_id},{"type",data_type},{"content",content}};if(!room_id.empty())j["room_id"]=room_id;return j;}};
struct Threepid{std::string medium,address,user_id;int64_t validated_at,added_at;json to_json()const{return{{"medium",medium},{"address",address},{"user_id",user_id},{"validated_at",validated_at},{"added_at",added_at}};}};
struct AccessToken{std::string token,user_id,device_id;int64_t valid_until_ms,last_validated;bool used;json to_json()const{return{{"token",token},{"user_id",user_id},{"device_id",device_id},{"valid_until_ms",valid_until_ms},{"last_validated",last_validated},{"used",used}};}};
struct LoginToken{std::string token,user_id;int64_t expiry_ts;json to_json()const{return{{"token",token},{"user_id",user_id},{"expiry_ts",expiry_ts}};}};
struct OpenIdToken{std::string token,user_id,server_name;int64_t expires_in,created_at;json to_json()const{return{{"access_token",token},{"token_type","Bearer"},{"matrix_server_name",server_name},{"expires_in",expires_in}};}};
struct RegistrationToken{std::string token,user_id;int uses_allowed,pending,completed;int64_t expiry_time;json to_json()const{return{{"token",token},{"uses_allowed",uses_allowed},{"pending",pending},{"completed",completed},{"expiry_time",expiry_time}};}};
struct UIAuthSession{std::string session_id;json flows,params,completed;int64_t created_at,expiry_time;json to_json()const{return{{"session",session_id},{"flows",flows},{"params",params},{"completed",completed}};}};
struct PusherData{std::string user_name,app_id,pushkey,kind,app_display_name,device_display_name,lang,profile_tag;json data;int64_t last_stream_ordering,last_success,failing_since;bool enabled;json to_json()const{json j{{"user_name",user_name},{"app_id",app_id},{"pushkey",pushkey},{"kind",kind},{"app_display_name",app_display_name},{"lang",lang},{"enabled",enabled}};if(!device_display_name.empty())j["device_display_name"]=device_display_name;if(!data.is_null())j["data"]=data;return j;}};
struct SearchEntryData{std::string event_id,room_id,key,value;int64_t stream_ordering,origin_server_ts;json to_json()const{return{{"event_id",event_id},{"room_id",room_id},{"key",key},{"value",value},{"stream_ordering",stream_ordering},{"origin_server_ts",origin_server_ts}};}};
struct EventRelation{std::string event_id,relates_to_id,relation_type,aggregation_key;json to_json()const{json j{{"event_id",event_id},{"relates_to_id",relates_to_id},{"relation_type",relation_type}};if(!aggregation_key.empty())j["aggregation_key"]=aggregation_key;return j;}};
struct ThreadInfo{std::string root_event_id,latest_event_id;int64_t count;std::vector<std::string> participants;json to_json()const{json j{{"root_event_id",root_event_id},{"latest_event_id",latest_event_id},{"count",count},{"participants",participants}};return j;}};
struct NotificationCount{std::string room_id;int64_t notification_count,highlight_count;json to_json()const{return{{"room_id",room_id},{"notification_count",notification_count},{"highlight_count",highlight_count}};}};
struct ServerKey{std::string server_name,key_id,public_key,private_key;int64_t valid_until_ts,expired_ts;json to_json()const{return{{"server_name",server_name},{"key_id",key_id},{"public_key",public_key},{"valid_until_ts",valid_until_ts},{"expired_ts",expired_ts}};}};
struct FederationDestination{std::string destination;int retry_interval,failure_count;int64_t last_success,last_failure,next_retry;bool reachable;json to_json()const{return{{"destination",destination},{"retry_interval",retry_interval},{"failure_count",failure_count},{"last_success",last_success},{"last_failure",last_failure},{"next_retry",next_retry},{"reachable",reachable}};}};
struct AppServiceDef{std::string id,url,as_token,hs_token,sender_localpart;json namespaces,rate_limited;bool enabled;json to_json()const{return{{"id",id},{"url",url},{"sender_localpart",sender_localpart},{"namespaces",namespaces},{"enabled",enabled},{"rate_limited",rate_limited}};}};
struct RateLimitBucket{std::string key;double tokens,max_tokens,refill_rate;int64_t last_refill;json to_json()const{return{{"key",key},{"tokens",tokens},{"max_tokens",max_tokens},{"refill_rate",refill_rate},{"last_refill",last_refill}};}};
struct RoomPermissions{std::string user_id,room_id;int64_t power_level;bool can_send,can_invite,can_kick,can_ban,can_redact,can_set_state;json to_json()const{return{{"user_id",user_id},{"room_id",room_id},{"power_level",power_level},{"can_send",can_send},{"can_invite",can_invite},{"can_kick",can_kick},{"can_ban",can_ban},{"can_redact",can_redact},{"can_set_state",can_set_state}};}};
struct RateLimitConfig{int64_t per_second,burst_count;bool enabled;json to_json()const{return{{"per_second",per_second},{"burst_count",burst_count},{"enabled",enabled}};}};
struct SSOProvider{std::string idp_id,idp_name,idp_icon,idp_brand,brand_icon_url,discovery_url,authorization_url,token_url,userinfo_url,client_id,scopes;json to_json()const{return{{"idp_id",idp_id},{"idp_name",idp_name},{"idp_icon",idp_icon},{"idp_brand",idp_brand},{"brand_icon_url",brand_icon_url},{"scopes",scopes}};}};
struct RoomDirectoryEntry{std::string room_id,name,topic,canonical_alias;int64_t num_joined_members;bool world_readable,guest_can_join;json to_json()const{return{{"room_id",room_id},{"name",name},{"topic",topic},{"canonical_alias",canonical_alias},{"num_joined_members",num_joined_members},{"world_readable",world_readable},{"guest_can_join",guest_can_join}};}};
struct UserDirectoryEntry{std::string user_id,display_name,avatar_url;int64_t shared_rooms;json to_json()const{return{{"user_id",user_id},{"display_name",display_name},{"avatar_url",avatar_url},{"shared_rooms",shared_rooms}};}};
struct PaginationToken{int64_t stream_ordering,topological_ordering;std::string room_id,direction;bool is_valid()const{return stream_ordering>=0;}json to_json()const{return{{"stream_ordering",stream_ordering},{"topological_ordering",topological_ordering},{"room_id",room_id},{"direction",direction}};}};
struct SyncToken{std::string token;int64_t events_stream,presence_stream,receipts_stream,typing_stream,to_device_stream,device_lists_stream,account_data_stream;json to_json()const{return{{"token",token},{"events_stream",events_stream},{"presence_stream",presence_stream},{"receipts_stream",receipts_stream},{"typing_stream",typing_stream},{"to_device_stream",to_device_stream},{"device_lists_stream",device_lists_stream},{"account_data_stream",account_data_stream}};}};
struct RoomSummary{std::string room_id;std::vector<std::string> heroes;int64_t joined_member_count,invited_member_count;json to_json()const{return{{"room_id",room_id},{"m.heroes",heroes},{"m.joined_member_count",joined_member_count},{"m.invited_member_count",invited_member_count}};}};
struct RoomVersion{std::string version,status;int priority;json features;json to_json()const{return{{"version",version},{"status",status},{"features",features}};}};
struct MSCFeature{std::string msc_id,description,status;bool enabled_by_default;json to_json()const{return{{"msc_id",msc_id},{"description",description},{"status",status},{"enabled_by_default",enabled_by_default}};}};
struct BackupVersion{std::string version,algorithm,auth_data;int64_t count,etag,created_at;json to_json()const{return{{"version",version},{"algorithm",algorithm},{"auth_data",json::parse(auth_data)},{"count",count},{"etag",std::to_string(etag)},{"created_at",created_at}};}};
struct BackupKey{std::string room_id,session_id,key_data;json to_json()const{return{{"room_id",room_id},{"session_id",session_id},{"key_data",json::parse(key_data)}};}};
struct DehydratedDevice{std::string user_id,device_id,device_data;int64_t created_at;json to_json()const{return{{"user_id",user_id},{"device_id",device_id},{"device_data",json::parse(device_data)},{"created_at",created_at}};}};
struct CrossSigningKey{std::string user_id,key_type,public_key;json signatures;json to_json()const{return{{"user_id",user_id},{"key_type",key_type},{"public_key",public_key},{"signatures",signatures}};}};
struct UserSignature{std::string signed_user_id,signer_user_id,signer_device_id,signature;json to_json()const{return{{"signed_user_id",signed_user_id},{"signer_user_id",signer_user_id},{"signer_device_id",signer_device_id},{"signature",signature}};}};
struct OneTimeKey{std::string user_id,device_id,algorithm,key_id,key_json;json to_json()const{return{{"user_id",user_id},{"device_id",device_id},{"algorithm",algorithm},{"key_id",key_id},{"key_json",json::parse(key_json)}};}};
struct FallbackKey{std::string user_id,device_id,algorithm,key_json;bool used;json to_json()const{return{{"user_id",user_id},{"device_id",device_id},{"algorithm",algorithm},{"key_json",json::parse(key_json)},{"used",used}};}};
struct DeviceKeys{std::string user_id,device_id;std::vector<std::string> algorithms;json keys,signatures;json to_json()const{return{{"user_id",user_id},{"device_id",device_id},{"algorithms",algorithms},{"keys",keys},{"signatures",signatures}};}};
struct PushGatewayConfig{std::string gateway_type,server_url,auth_token;json additional;json to_json()const{return{{"gateway_type",gateway_type},{"server_url",server_url},{"auth_token",auth_token},{"additional",additional}};}};
struct FederationTransaction{std::string transaction_id,origin,destination;int64_t origin_server_ts;std::vector<std::string> pdus,edus;json to_json()const{return{{"transaction_id",transaction_id},{"origin",origin},{"destination",destination},{"origin_server_ts",origin_server_ts},{"pdus",pdus},{"edus",edus}};}};
struct IdentityLookupResult{std::string medium,address,user_id;bool found;json to_json()const{return{{"medium",medium},{"address",address},{"user_id",user_id},{"found",found}};}};
struct EventReport{int64_t id,received_ts;std::string room_id,event_id,user_id,reason,content;json to_json()const{return{{"id",id},{"received_ts",received_ts},{"room_id",room_id},{"event_id",event_id},{"user_id",user_id},{"reason",reason},{"content",content}};}};
struct BackgroundUpdate{std::string name,status;int64_t total_rows,processed_rows;double progress_pct;json to_json()const{return{{"name",name},{"status",status},{"total_rows",total_rows},{"processed_rows",processed_rows},{"progress_pct",progress_pct}};}};
struct SchemaMigration{std::string version,description,file;int64_t applied_at;bool success;json to_json()const{return{{"version",version},{"description",description},{"file",file},{"applied_at",applied_at},{"success",success}};}};
struct RetentionPolicy{std::string room_id;int64_t max_lifetime,min_lifetime;json to_json()const{return{{"room_id",room_id},{"max_lifetime",max_lifetime},{"min_lifetime",min_lifetime}};}};
struct ServerInfo{std::string server_name,software_name,software_version;bool supports_federation;json features;json to_json()const{return{{"server_name",server_name},{"software_name",software_name},{"software_version",software_version},{"supports_federation",supports_federation},{"features",features}};}};
struct WebSocketMessage{std::string type,room_id;json payload;json to_json()const{return{{"type",type},{"room_id",room_id},{"payload",payload}};}};
struct CacheEntry{std::string key,cache_name;json value;int64_t expiry,created_at;json to_json()const{return{{"key",key},{"cache_name",cache_name},{"value",value},{"expiry",expiry},{"created_at",created_at}};}};
struct ConnectionLimit{std::string source;int64_t current,max_allowed;json to_json()const{return{{"source",source},{"current",current},{"max_allowed",max_allowed}};}};
}
